theme: jekyll-theme-minimal
title: Istio Hands-On
description: Learning about Istio's capabilities using the Bookinfo example app on Minikube as platform
show_downloads: False
navigation:
  - title: Overview
    url: /
  - title: 1. Setting up Minikube and Istio
    url: docs/exercise1
  - title: 2. Installing Telemetry Add-ons and Bookinfo
    url: docs/exercise2
  - title: 3. Traffic Management
    url: docs/exercise3
  - title: 4. Observability
    url: docs/exercise4
  - title: 5. Test
    url: docs/exercise5

