theme: jekyll-theme-minimal
title: Istio Hands-On
updated: 12.1.2023
logo: images/istio-logo.png
show_downloads: False
navigation:
  - title: Overview
    url: /
  - title: 1. Setting up Minikube and Istio
    url: docs/exercise1
  - title: 2. Installing Bookinfo
    url: docs/exercise2
  - title: 3. Observability
    url: docs/exercise3
  - title: 4. Traffic Management 1
    url: docs/exercise4
  - title: 5. Traffic Management 2
    url: docs/exercise5
  - title: APPENDIX - Important commands
    url: docs/appendix
